services:
  - type: web
    name: mymeal-backend
    runtime: node
    rootDir: backend_node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: turntable.proxy.rlwy.net
      - key: DB_PORT
        value: 28628
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: xGrVfpmEQuZtqdKODRlEjaxbMJwJDbBc
      - key: DB_NAME
        value: railway